In [1]:
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import pickle
import sklearn
import sklearn.metrics

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
dataset = pd.read_csv('/content/drive/MyDrive/Dataset_Image_2023/FeatureEkstrasi.csv')

In [4]:
dataset

carbon_values     ndvi1     ndvi2     ndvi3     ndvi4     ndvi5  \
0             28.65  0.068783  0.050505  0.053659  0.072464  0.072165   
1             28.65  0.076190  0.064039  0.064039  0.072464  0.076923   
2             28.65  0.068627  0.068627  0.064039  0.049505  0.043902   
3             28.65  0.088803  0.103704  0.108434  0.121739  0.111111   
4             28.65  0.069597  0.091633  0.089286  0.093117  0.088968   
...             ...       ...       ...       ...       ...       ...   
4855          41.22  0.072464  0.069231  0.076923  0.084507  0.092105   
4856          41.22  0.102564  0.076923  0.085714  0.088435  0.096990   
4857          41.22  0.099237  0.102990  0.108772  0.103448  0.103943   
4858          41.22  0.083969  0.096085  0.100671  0.102941  0.095652   
4859          41.22  0.098507  0.093567  0.112540  0.106383  0.094077   

         ndvi6     ndvi7     ndvi8     ndvi9  ...   energy4  correlation1  \
0     0.067358  0.069307  0.056995  0.051546  ...  0.132393      0.657738   
1     0.076923  0.062802  0.057143  0.066038  ...  0.100985      0.915818   
2     0.038462  0.042654  0.052632  0.062802  ...  0.108726      0.865050   
3     0.102662  0.099237  0.089431  0.076923  ...  0.113822      0.517559   
4     0.075758  0.084746  0.081081  0.072340  ...  0.059734      0.575239   
...        ...       ...       ...       ...  ...       ...           ...   
4855  0.095238  0.097744  0.090226  0.082192  ...  0.057907      0.523516   
4856  0.105058  0.109005  0.109170  0.101045  ...  0.042856      0.533556   
4857  0.095082  0.097902  0.097561  0.096525  ...  0.112474      0.421108   
4858  0.093878  0.096085  0.097473  0.098814  ...  0.059605      0.559740   
4859  0.080000  0.090909  0.090196  0.076305  ...  0.046889      0.511853   

      correlation2  correlation3  correlation4      asm1      asm2      asm3  \
0         0.565241      0.681647      0.439020  0.017531  0.017528  0.017531   
1         0.794983      0.883567      0.848795  0.011717  0.009599  0.010997   
2         0.729176      0.790153      0.720102  0.015571  0.012195  0.013481   
3         0.384429      0.737843      0.262242  0.012346  0.013565  0.012593   
4         0.354388      0.769901      0.426414  0.003435  0.003522  0.004017   
...            ...           ...           ...       ...       ...       ...   
4855      0.287500      0.826159      0.517837  0.003407  0.003338  0.003698   
4856      0.373974      0.846401      0.462414  0.001805  0.001718  0.002346   
4857      0.161338      0.772755      0.292387  0.011852  0.012651  0.012099   
4858      0.334456      0.824508      0.543180  0.003546  0.003353  0.004141   
4859      0.324747      0.849125      0.507561  0.002085  0.002128  0.002687   

          asm4  HST  
0     0.017528  1.0  
1     0.010198  1.0  
2     0.011821  1.0  
3     0.012955  1.0  
4     0.003568  1.0  
...        ...  ...  
4855  0.003353  3.0  
4856  0.001837  3.0  
4857  0.012651  3.0  
4858  0.003553  3.0  
4859  0.002199  3.0  

[4860 rows x 426 columns]

In [5]:
dataset.dtypes

carbon_values    float64
ndvi1            float64
ndvi2            float64
ndvi3            float64
ndvi4            float64
                  ...   
asm1             float64
asm2             float64
asm3             float64
asm4             float64
HST              float64
Length: 426, dtype: object

In [6]:
dataset.isnull().values.any()

False

In [7]:
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, 0].values
z = dataset.iloc[:,-1].values

In [8]:
X

array([[0.06878307, 0.05050505, 0.05365854, ..., 0.01752782, 0.01753086,
        0.01752782],
       [0.07619048, 0.06403941, 0.06403941, ..., 0.00959937, 0.01099723,
        0.0101979 ],
       [0.06862745, 0.06862745, 0.06403941, ..., 0.01219459, 0.01348131,
        0.01182133],
       ...,
       [0.09923664, 0.10299003, 0.10877193, ..., 0.01265051, 0.01209877,
        0.01265051],
       [0.08396947, 0.09608541, 0.10067114, ..., 0.00335326, 0.00414127,
        0.00355277],
       [0.09850746, 0.09356725, 0.11254019, ..., 0.00212787, 0.00268728,
        0.00219856]])

In [9]:
len(X)

4860

In [10]:
y

array([28.65, 28.65, 28.65, ..., 41.22, 41.22, 41.22])

In [11]:
len(y)

4860

In [12]:
z

array([1., 1., 1., ..., 3., 3., 3.])

In [13]:
len(z)

4860

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test, z_train, z_test = train_test_split(X, y,z, test_size=0.2, random_state=42)

#SVR Model

In [15]:
from sklearn.svm import SVR

model_svr_rbf = SVR(kernel="rbf")
model_svr_linear = SVR(kernel="linear")
model_svr_poly = SVR(kernel="poly")

model_svr_rbf.fit(X_train, y_train)
print("score svr kernel rbf: ", model_svr_rbf.score(X_test, y_test))

model_svr_linear.fit(X_train, y_train)
print("score svr kernel linear: ", model_svr_linear.score(X_test, y_test))

model_svr_poly.fit(X_train, y_train)
print("score svr kernel poly: ", model_svr_poly.score(X_test, y_test))



score svr kernel rbf:  -0.11788217957078162
score svr kernel linear:  0.07433550292899471
score svr kernel poly:  -0.2670939074516121


In [24]:
from sklearn.metrics import mean_squared_error
import math

y_pred = model_svr_rbf.predict(X_test)
MSE = mean_squared_error(y_test, y_pred)

RMSE = math.sqrt(MSE)
print("Root Mean Square Error SVR Kernel RBF:", RMSE)

mape = np.mean(np.abs((y_test - y_pred)/y_test))*100
print("MAE(%)",round(mape,2),"%")

Root Mean Square Error SVR Kernel RBF:

8.970060658010084
MAE(%) 28.51 %


In [25]:
y_pred = model_svr_linear.predict(X_test)

MSE = mean_squared_error(y_test, y_pred)

RMSE = math.sqrt(MSE)
print("Root Mean Square Error SVR Kernel linear:", RMSE)
mape = np.mean(np.abs((y_test - y_pred)/y_test))*100
print("MAE(%)",round(mape,2),"%")

Root Mean Square Error SVR Kernel linear:

8.162518280692277
MAE(%) 24.94 %


In [26]:
y_pred = model_svr_poly.predict(X_test)

MSE = mean_squared_error(y_test, y_pred)

RMSE = math.sqrt(MSE)
print("Root Mean Square Error SVR Kernel Poly:", RMSE)
mape = np.mean(np.abs((y_test - y_pred)/y_test))*100
print("MAE(%)",round(mape,2),"%")

Root Mean Square Error SVR Kernel Poly:

9.549964665636411
MAE(%) 29.06 %


#Multiple Linear Regression & OLS

In [19]:
# #linear regression

from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

model.score(X_test, y_test)

0.1614276585294071

In [20]:
import statsmodels.api as sm
X_train_ols = sm.add_constant(X)
model = sm.OLS(y, X_train_ols).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.299
Model:                            OLS   Adj. R-squared:                  0.249
Method:                 Least Squares   F-statistic:                     5.967
Date:                Fri, 22 Dec 2023   Prob (F-statistic):          5.79e-179
Time:                        23:54:24   Log-Likelihood:                -16476.
No. Observations:                4860   AIC:                         3.360e+04
Df Residuals:                    4535   BIC:                         3.571e+04
Df Model:                         324                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         20.7348      3.521      5.889      0.0